2022-08-03 12:10:50,679 - 62 - logging_info.py - INFO - 108
2022-08-03 12:30:05,971 - 33 - INFO - 108
2022-08-03 12:30:54,966 - 33 - INFO - 108
2022-08-03 12:31:48,655 - 33 - INFO - 108
2022-08-03 12:31:51,661 - 33 - INFO - 'ModbusIOException' object has no attribute 'registers'
2022-08-03 12:31:51,662 - 33 - INFO - 'AttributeError' object has no attribute 'values'
2022-08-03 12:31:54,666 - 218 - ERROR - Connection to (192.168.1.254, 502) failed: timed out
2022-08-03 12:31:57,670 - 218 - ERROR - Connection to (192.168.1.254, 502) failed: timed out
2022-08-03 12:31:57,672 - 33 - INFO - Modbus Error: [Connection] Failed to connect[ModbusTcpClient(192.168.1.254:502)]
2022-08-03 12:33:45,844 - 33 - INFO - 108
2022-08-03 12:35:02,244 - 33 - INFO - 108
2022-08-03 12:40:28,435 - 33 - INFO - 108
2022-08-03 12:41:01,813 - 33 - INFO - 108
2022-08-03 12:41:04,818 - 33 - INFO - 'ModbusIOException' object has no attribute 'registers'
2022-08-03 12:41:04,819 - 33 - INFO - 'AttributeError' object has no attribute 'values'
2022-08-03 12:41:07,824 - 218 - ERROR - Connection to (192.168.1.254, 502) failed: timed out
2022-08-03 12:41:10,829 - 218 - ERROR - Connection to (192.168.1.254, 502) failed: timed out
2022-08-03 12:41:10,831 - 33 - INFO - Modbus Error: [Connection] Failed to connect[ModbusTcpClient(192.168.1.254:502)]
2022-08-03 12:42:02,626 - 33 - INFO - Modbus Error: [Connection] Failed to connect[ModbusTcpClient(192.168.1.254:502)]
2022-08-03 12:42:05,632 - 218 - ERROR - Connection to (192.168.1.254, 502) failed: timed out
2022-08-03 12:42:08,638 - 218 - ERROR - Connection to (192.168.1.254, 502) failed: timed out
2022-08-03 12:42:08,641 - 33 - INFO - Modbus Error: [Connection] Failed to connect[ModbusTcpClient(192.168.1.254:502)]
2022-08-03 12:42:11,646 - 218 - ERROR - Connection to (192.168.1.254, 502) failed: timed out
2022-08-03 12:42:14,653 - 218 - ERROR - Connection to (192.168.1.254, 502) failed: timed out
2022-08-03 12:42:14,656 - 33 - INFO - Modbus Error: [Connection] Failed to connect[ModbusTcpClient(192.168.1.254:502)]
2022-08-03 12:43:00,028 - 33 - INFO - 109
2022-08-03 12:44:22,760 - 33 - INFO - 108
2022-08-03 12:44:25,963 - 33 - INFO - 'ModbusIOException' object has no attribute 'registers'
2022-08-03 12:44:25,965 - 33 - INFO - 'AttributeError' object has no attribute 'values'
2022-08-03 12:44:52,267 - 33 - INFO - 108
2022-08-03 12:44:55,507 - 33 - INFO - 'ModbusIOException' object has no attribute 'registers'
2022-08-03 12:44:55,509 - 33 - INFO - 'AttributeError' object has no attribute 'values'
2022-08-04 11:21:22,269 - 33 - INFO - Replacement index 1 out of range for positional args tuple
2022-08-04 11:21:22,269 - 33 - INFO - 'IndexError' object has no attribute 'values'
2022-08-04 11:21:22,269 - 33 - INFO - 'IndexError' object has no attribute 'values'
2022-08-04 11:21:51,609 - 33 - INFO - Replacement index 1 out of range for positional args tuple
2022-08-04 11:21:51,610 - 33 - INFO - 'IndexError' object has no attribute 'values'
2022-08-04 11:21:51,610 - 33 - INFO - 'IndexError' object has no attribute 'values'
2022-08-04 11:24:10,348 - 33 - INFO - Replacement index 1 out of range for positional args tuple
2022-08-04 11:24:10,348 - 33 - INFO - 'IndexError' object has no attribute 'values'
2022-08-04 11:24:10,348 - 33 - INFO - 'IndexError' object has no attribute 'values'
2022-08-04 11:25:01,938 - 33 - INFO - Replacement index 1 out of range for positional args tuple
2022-08-04 11:25:01,938 - 33 - INFO - 'IndexError' object has no attribute 'values'
2022-08-04 11:25:01,938 - 33 - INFO - 'IndexError' object has no attribute 'values'
2022-08-04 11:25:15,284 - 33 - INFO - Replacement index 1 out of range for positional args tuple
2022-08-04 11:25:15,285 - 33 - INFO - 'IndexError' object has no attribute 'values'
2022-08-04 11:25:15,285 - 33 - INFO - 'IndexError' object has no attribute 'values'
2022-08-04 11:25:19,954 - 33 - INFO - Replacement index 1 out of range for positional args tuple
2022-08-04 11:25:19,954 - 33 - INFO - 'IndexError' object has no attribute 'values'
2022-08-04 11:25:19,954 - 33 - INFO - 'IndexError' object has no attribute 'values'
