2022-08-29 16:51:39,083 - ERROR - INVALID_INFO - Error_in_set_bod_configurations
NoneType: None
2022-08-29 16:52:21,258 - ERROR - INVALID_INFO - Error_in_set_bod_configurations
NoneType: None
2022-08-29 16:53:29,641 - ERROR - INVALID_INFO - Error_in_set_bod_configurations
NoneType: None
2022-08-29 16:55:00,789 - ERROR - list index out of range
Traceback (most recent call last):
  File "/home/pimkc/Desktop/Wiras/After_First_Review_26_7/Sensor_Management/bod_sensor_management.py", line 286, in set_bod_configurations
    SensorGetRegisterCounts[initial_index:final_index]: list(
IndexError: list index out of range
2022-08-29 16:55:41,670 - ERROR - list index out of range
Traceback (most recent call last):
  File "/home/pimkc/Desktop/Wiras/After_First_Review_26_7/Sensor_Management/bod_sensor_management.py", line 286, in set_bod_configurations
    SensorGetRegisterCounts[initial_index:final_index]: list(
IndexError: list index out of range
2022-08-29 17:07:16,995 - INFO - Configurations added successfully
2022-08-29 17:10:48,177 - ERROR - [Errno 2] No such file or directory: 'Configurations_and_Errors/Sensor_Configurations.json'
Traceback (most recent call last):
  File "/home/pimkc/Desktop/Wiras/After_First_Review_26_7/Sensor_Management/bod_sensor_management.py", line 89, in get_bod_configurations
    with open(Configurations_File, read_mode, encoding="utf-8") as file:
FileNotFoundError: [Errno 2] No such file or directory: 'Configurations_and_Errors/Sensor_Configurations.json'
2022-08-29 17:10:48,179 - ERROR - [Errno 2] No such file or directory: 'Configurations_and_Errors/Sensor_Configurations.json'
Traceback (most recent call last):
  File "/home/pimkc/Desktop/Wiras/After_First_Review_26_7/Sensor_Management/bod_sensor_management.py", line 288, in set_bod_configurations
    with open(Configurations_File, read_write_mode, encoding="utf-8") as file:
FileNotFoundError: [Errno 2] No such file or directory: 'Configurations_and_Errors/Sensor_Configurations.json'
